const mongoose = require('mongoose');

var refundSchema = mongoose.Schema({

      //AmazonOrderID: { type: String, unique: true },
      AmazonOrderID: { type: String, unique: true},
      userid : String,
      SellerSKU: String,
      rundate: String,
      customerid: String,
      feeType0: String,
      feeType1: String,
      feeType2: String,
      feeType3: String,
      feeType4: String,
      feeType5: String,
      feeTypeprice0: String,
      feeTypeprice1: String,
      feeTypeprice2: String,
      feeTypeprice3: String,
      feeTypeprice4: String,
      feeTypeprice5: String,
      feeTypecurrency0: String,
      feeTypecurrency1: String,
      feeTypecurrency2: String,
      feeTypecurrency3: String,
      feeTypecurrency4: String,
      feeTypecurrency5: String,
      chargeType0: String,
      chargeType1: String,
      chargeType2: String,
      chargeType3: String,
      chargeType4: String,
      chargeType5: String,
      chargeTypeprice0: String,
      chargeTypeprice1: String,
      chargeTypeprice2: String,
      chargeTypeprice3: String,
      chargeTypeprice4: String,
      chargeTypeprice5: String,
      chargeTypecurrency0: String,
      chargeTypecurrency1: String,
      chargeTypecurrency2: String,
      chargeTypecurrency3: String,
      chargeTypecurrency4: String,
      chargeTypecurrency5: String,
});


module.exports = mongoose.model("refund", refundSchema);
